### PR TITLE
Merge dev into master

### PR DESCRIPTION
**Pull request by bwjtkw**

### CODE REVIEW

**Comment by bwjtkw** [comment]
!testme

**Comment by tituspijean** [comment]
Out of curiosity, why have you closed this PR and opened the same one right after?

**Comment by oiseauroch** [comment]
Because we're not yet familiar with github and yunohost workflow now and we try things to understand how it works !

**Comment by tituspijean** [comment]
OK ! :) Then, if I may bring some experience to your experiments:
PRs can be used for "work in progress" development: if you add commits to the branch they are created from, the commits will show up in the PR automagically. You can then use `!testme` whenever you want and multiple times in the same PR: the bot will use the available code at the time. ;)

Thanks for your contributions! :)

**Comment by oiseauroch** [comment]
Ok thanks for advice

**Pull request closed without merging**
